const { execSync } = require('child_process');
const path = require('path');
const fs = require('fs');

const GITHUB_TOKEN = process.env.GITHUB_TOKEN;
const REPO = process.env.GITHUB_REPOSITORY; // owner/repo

if (!GITHUB_TOKEN || !REPO) {
  console.error('GITHUB_TOKEN and GITHUB_REPOSITORY environment variables are required.');
  process.exit(1);
}

async function getAlerts() {
  console.log(`Fetching Dependabot alerts for ${REPO}...`);
  const response = await fetch(`https://api.github.com/repos/${REPO}/dependabot/alerts?state=open`, {
    headers: {
      Authorization: `token ${GITHUB_TOKEN}`,
      Accept: 'application/vnd.github+json',
      'X-GitHub-Api-Version': '2022-11-28',
    },
  });

  if (!response.ok) {
    throw new Error(`Failed to fetch alerts: ${response.statusText}`);
  }

  return await response.json();
}

async function createPR(branchName, title, body) {
  console.log(`Creating PR for branch ${branchName}...`);
  const response = await fetch(`https://api.github.com/repos/${REPO}/pulls`, {
    method: 'POST',
    headers: {
      Authorization: `token ${GITHUB_TOKEN}`,
      Accept: 'application/vnd.github+json',
      'X-GitHub-Api-Version': '2022-11-28',
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      title,
      body,
      head: branchName,
      base: 'main',
    }),
  });

  if (!response.ok) {
    const errorData = await response.json();
    console.error('PR Creation error details:', JSON.stringify(errorData, null, 2));
    throw new Error(`Failed to create PR: ${response.statusText}`);
  }

  const pr = await response.json();
  console.log(`PR created: ${pr.html_url}`);
  return pr;
}

function parseVersion(range) {
  // Simple regex to extract the first semantic version
  const match = range.match(/\d+\.\d+\.\d+/);
  return match ? match[0] : null;
}

async function fixAlert(alert) {
  const pkgName = alert.dependency.package.name;
  const manifestPath = alert.dependency.manifest_path;
  const patchedRange = alert.security_advisory.patched_versions;
  const targetVersion = parseVersion(patchedRange);

  if (!targetVersion) {
    console.warn(`Could not parse target version from range: ${patchedRange} for ${pkgName}`);
    return;
  }

  console.log(`\nFixing ${pkgName} to ${targetVersion} in ${manifestPath}...`);

  const manifestDir = path.dirname(manifestPath);
  const branchName = `fix/dependabot-${pkgName}-${Date.now()}`;

  try {
    // 1. Create branch
    execSync(`git checkout -b ${branchName}`, { stdio: 'inherit' });

    // 2. Install package
    const cmd = `npm install ${pkgName}@${targetVersion}`;
    console.log(`Running: ${cmd} in ${manifestDir}`);
    execSync(cmd, { cwd: manifestDir === '.' ? process.cwd() : manifestDir, stdio: 'inherit' });

    // 3. Build & Test
    console.log('Running Sanity Checks...');
    execSync('npm run build', { cwd: manifestDir === '.' ? process.cwd() : manifestDir, stdio: 'inherit' });
    
    // Add coverage check if it's resume-site
    if (manifestDir.includes('resume-site')) {
        console.log('Running test coverage...');
        execSync('npm run test:coverage', { cwd: manifestDir, stdio: 'inherit' });
    }

    // 4. Commit and Push
    execSync('git add .', { stdio: 'inherit' });
    execSync(`git commit -m "security: fix ${pkgName} vulnerability (GHSA-${alert.security_advisory.ghsa_id})"`, { stdio: 'inherit' });
    execSync(`git push origin ${branchName}`, { stdio: 'inherit' });

    // 5. Create PR
    const prBody = `
### Automated Security Fix
- **Alert**: ${alert.security_advisory.summary}
- **Package**: ${pkgName}
- **Target Version**: ${targetVersion}
- **Vulnerability**: [${alert.security_advisory.ghsa_id}](https://github.com/advisories/${alert.security_advisory.ghsa_id})

This PR was automatically generated by the Dependabot Auto-Fix monitor.
    `;
    const pr = await createPR(branchName, `Fix ${pkgName} Security Vulnerability`, prBody);

    // 6. Notify
    const notify = require('./notify');
    await notify(`Fix PR Created: ${pkgName}`, `A new security fix PR has been created for ${pkgName}: ${pr.html_url}`);

    // Return to main
    execSync('git checkout main', { stdio: 'inherit' });

  } catch (err) {
    console.error(`Failed to fix alert for ${pkgName}:`, err.message);
    execSync('git checkout main', { stdio: 'inherit' });
  }
}

async function main() {
  try {
    const alerts = await getAlerts();
    const openAlerts = alerts.filter(a => a.state === 'open');
    console.log(`Found ${openAlerts.length} open alerts.`);

    for (const alert of openAlerts) {
      await fixAlert(alert);
    }
  } catch (err) {
    console.error('Main execution error:', err.message);
    process.exit(1);
  }
}

main();
